export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS ",
    REMOVE_SELECTED_PRODUCTS: " REMOVE_SELECTED_PRODUCTS ",
    FILTER_PRODUCTS_BY_CATEGORY:"FILTER_PRODUCTS_BY_CATEGORY",
    TAB_CASSES_COVID:"TAB_CASSES_COVID"
};